/// Flutter icons Bottom_nav_bar
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottom_nav_bar
///      fonts:
///       - asset: fonts/Bottom_nav_bar.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bottom_nav_bar {
  Bottom_nav_bar._();

  static const _kFontFam = 'Bottom_nav_bar';
  static const String? _kFontPkg = null;

  static const IconData home_bold = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history_bold = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistic_bold = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData statistic = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_bold = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
